# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20170604_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='url名称')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('created_time', models.DateTimeField(verbose_name='录入时间')),
            ],
        ),
    ]
