# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500, verbose_name='美句')),
                ('created_time', models.DateTimeField(verbose_name='收入时间')),
            ],
        ),
    ]
