# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='originate_from',
            field=models.CharField(blank=True, max_length=50, verbose_name='出自'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(max_length=500, verbose_name='美句'),
        ),
    ]
