# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20170606_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
