# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='ip地址')),
                ('city', models.CharField(max_length=20, verbose_name='所在地')),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Post')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
    ]
