# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170606_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='city',
            field=models.CharField(max_length=20, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='ip地址'),
        ),
    ]
